### ISSUE TITLE
PIN Lock

### ISSUE THREAD

**Issue by jappyjan** [joba-1/Joba_JbdBms#4]
Hello,

First of all: this is an awesome library! Well written and performs perfectly!

I locked my BMS (out of curiosity) with a 4 digit Pin Code (0000).
Since then i am unable to set the mosfet state using this library.
I am also unable to set the state using the BLE module and the App until i enter the pin code there.

Is there a way to either remove the Pin Code again or to tell this library to unock the BMS using the pin code?

**Comment by joba-1** [comment]
Danke für die Blumen :)
Leider kann ich bei der PIN nicht helfen. Meine Lib kann keine Pin zurücksetzten. 
Ich hab gerade nochmal die Doku von Jiabaida durchgelesen, da wird nirgends eine Pin erwähnt - auch kein Factory Reset oder so was in der Art.
Ich würde an deiner Stelle mal bei denen anfragen - die waren mir gegenüber sehr hilfsbereit: https://jiabaidabms.com/en-de
